<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Rank_Math_Instant_Indexing\\phpseclib3\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Rank_Math_Instant_Indexing\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Rank_Math_Instant_Indexing\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'Rank_Math_Instant_Indexing\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'Rank_Math_Instant_Indexing\\Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'Rank_Math_Instant_Indexing\\ParagonIE\\ConstantTime\\' => array($vendorDir . '/paragonie/constant_time_encoding/src'),
    'Rank_Math_Instant_Indexing\\Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Rank_Math_Instant_Indexing\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'Rank_Math_Instant_Indexing\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'Rank_Math_Instant_Indexing\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Rank_Math_Instant_Indexing\\Google\\Service\\' => array($vendorDir . '/google/apiclient-services/src'),
    'Rank_Math_Instant_Indexing\\Google\\Auth\\' => array($vendorDir . '/google/auth/src'),
    'Rank_Math_Instant_Indexing\\Google\\' => array($vendorDir . '/google/apiclient/src'),
    'Rank_Math_Instant_Indexing\\Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
);
