<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit342aaef939e1485687016700445f585d
{
    public static $files = array (
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
        '7b11c4dc42b3b3023073cb14e519683c' => __DIR__ . '/..' . '/ralouphie/getallheaders/src/getallheaders.php',
        'a4a119a56e50fbb293281d9a48007e0e' => __DIR__ . '/..' . '/symfony/polyfill-php80/bootstrap.php',
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
        '8825ede83f2f289127722d4e842cf7e8' => __DIR__ . '/..' . '/symfony/polyfill-intl-grapheme/bootstrap.php',
        'e69f7f6ee287b969198c3c9d6777bd38' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/bootstrap.php',
        'b6b991a57620e2fb6b2f66f03fe9ddc2' => __DIR__ . '/..' . '/symfony/string/Resources/functions.php',
        '1f87db08236948d07391152dccb70f04' => __DIR__ . '/..' . '/google/apiclient-services/autoload.php',
        'decc78cc4436b1292c6c0d151b19445c' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
        'a8d3953fd9959404dd22d3dfcd0a79f0' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'fe1d4898277c26748a003292f432cd3b' => __DIR__ . '/..' . '/jetbrains/phpstorm-stubs/PhpStormStubsMap.php',
        '23c18046f52bef3eea034657bafda50f' => __DIR__ . '/..' . '/symfony/polyfill-php81/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Rank_Math_Instant_Indexing\\phpseclib3\\' => 38,
            'Rank_Math_Instant_Indexing\\Webmozart\\Assert\\' => 44,
            'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Php81\\' => 50,
            'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Php80\\' => 50,
            'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Mbstring\\' => 53,
            'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Intl\\Normalizer\\' => 60,
            'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Intl\\Grapheme\\' => 58,
            'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Ctype\\' => 50,
            'Rank_Math_Instant_Indexing\\Symfony\\Contracts\\Service\\' => 53,
            'Rank_Math_Instant_Indexing\\Symfony\\Contracts\\EventDispatcher\\' => 61,
            'Rank_Math_Instant_Indexing\\Symfony\\Component\\String\\' => 52,
            'Rank_Math_Instant_Indexing\\Symfony\\Component\\Finder\\' => 52,
            'Rank_Math_Instant_Indexing\\Symfony\\Component\\Filesystem\\' => 56,
            'Rank_Math_Instant_Indexing\\Symfony\\Component\\Console\\' => 53,
            'Rank_Math_Instant_Indexing\\Psr\\Log\\' => 35,
            'Rank_Math_Instant_Indexing\\Psr\\Http\\Message\\' => 44,
            'Rank_Math_Instant_Indexing\\Psr\\Http\\Client\\' => 43,
            'Rank_Math_Instant_Indexing\\Psr\\EventDispatcher\\' => 47,
            'Rank_Math_Instant_Indexing\\Psr\\Container\\' => 41,
            'Rank_Math_Instant_Indexing\\Psr\\Cache\\' => 37,
            'Rank_Math_Instant_Indexing\\PhpParser\\' => 37,
            'Rank_Math_Instant_Indexing\\ParagonIE\\ConstantTime\\' => 50,
            'Rank_Math_Instant_Indexing\\PackageVersions\\' => 43,
            'Rank_Math_Instant_Indexing\\Monolog\\' => 35,
            'Rank_Math_Instant_Indexing\\GuzzleHttp\\Psr7\\' => 43,
            'Rank_Math_Instant_Indexing\\GuzzleHttp\\Promise\\' => 46,
            'Rank_Math_Instant_Indexing\\GuzzleHttp\\' => 38,
            'Rank_Math_Instant_Indexing\\Google\\Service\\' => 42,
            'Rank_Math_Instant_Indexing\\Google\\Auth\\' => 39,
            'Rank_Math_Instant_Indexing\\Google\\' => 34,
            'Rank_Math_Instant_Indexing\\Firebase\\JWT\\' => 40,
            'Rank_Math_Instant_Indexing\\Fidry\\Console\\' => 41,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Rank_Math_Instant_Indexing\\phpseclib3\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
        ),
        'Rank_Math_Instant_Indexing\\Webmozart\\Assert\\' => 
        array (
            0 => __DIR__ . '/..' . '/webmozart/assert/src',
        ),
        'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Php81\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php81',
        ),
        'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Php80\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php80',
        ),
        'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Intl\\Normalizer\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer',
        ),
        'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Intl\\Grapheme\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-grapheme',
        ),
        'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'Rank_Math_Instant_Indexing\\Symfony\\Contracts\\Service\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/service-contracts',
        ),
        'Rank_Math_Instant_Indexing\\Symfony\\Contracts\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher-contracts',
        ),
        'Rank_Math_Instant_Indexing\\Symfony\\Component\\String\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/string',
        ),
        'Rank_Math_Instant_Indexing\\Symfony\\Component\\Finder\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/finder',
        ),
        'Rank_Math_Instant_Indexing\\Symfony\\Component\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/filesystem',
        ),
        'Rank_Math_Instant_Indexing\\Symfony\\Component\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/console',
        ),
        'Rank_Math_Instant_Indexing\\Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Rank_Math_Instant_Indexing\\Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-factory/src',
            1 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Rank_Math_Instant_Indexing\\Psr\\Http\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-client/src',
        ),
        'Rank_Math_Instant_Indexing\\Psr\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/event-dispatcher/src',
        ),
        'Rank_Math_Instant_Indexing\\Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Rank_Math_Instant_Indexing\\Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'Rank_Math_Instant_Indexing\\PhpParser\\' => 
        array (
            0 => __DIR__ . '/..' . '/nikic/php-parser/lib/PhpParser',
        ),
        'Rank_Math_Instant_Indexing\\ParagonIE\\ConstantTime\\' => 
        array (
            0 => __DIR__ . '/..' . '/paragonie/constant_time_encoding/src',
        ),
        'Rank_Math_Instant_Indexing\\PackageVersions\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/package-versions-deprecated/src/PackageVersions',
        ),
        'Rank_Math_Instant_Indexing\\Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'Rank_Math_Instant_Indexing\\GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'Rank_Math_Instant_Indexing\\GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'Rank_Math_Instant_Indexing\\GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'Rank_Math_Instant_Indexing\\Google\\Service\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/apiclient-services/src',
        ),
        'Rank_Math_Instant_Indexing\\Google\\Auth\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/auth/src',
        ),
        'Rank_Math_Instant_Indexing\\Google\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/apiclient/src',
        ),
        'Rank_Math_Instant_Indexing\\Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
        'Rank_Math_Instant_Indexing\\Fidry\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/fidry/console/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Google_AccessToken_Revoke' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_AccessToken_Verify' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_AuthHandler_AuthHandlerFactory' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_AuthHandler_Guzzle6AuthHandler' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_AuthHandler_Guzzle7AuthHandler' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Client' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Collection' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Exception' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Http_Batch' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Http_MediaFileUpload' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Http_REST' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Model' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Service' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Service_Exception' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Service_Resource' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Task_Composer' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Task_Exception' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Task_Retryable' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Task_Runner' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Google_Utils_UriTemplate' => __DIR__ . '/..' . '/google/apiclient/src/aliases.php',
        'Rank_Math_Instant_Indexing\\Attribute' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/Attribute.php',
        'Rank_Math_Instant_Indexing\\CURLStringFile' => __DIR__ . '/..' . '/symfony/polyfill-php81/Resources/stubs/CURLStringFile.php',
        'Rank_Math_Instant_Indexing\\Normalizer' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
        'Rank_Math_Instant_Indexing\\PhpToken' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/PhpToken.php',
        'Rank_Math_Instant_Indexing\\ReturnTypeWillChange' => __DIR__ . '/..' . '/symfony/polyfill-php81/Resources/stubs/ReturnTypeWillChange.php',
        'Rank_Math_Instant_Indexing\\Stringable' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/Stringable.php',
        'Rank_Math_Instant_Indexing\\UnhandledMatchError' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/UnhandledMatchError.php',
        'Rank_Math_Instant_Indexing\\ValueError' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/ValueError.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit342aaef939e1485687016700445f585d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit342aaef939e1485687016700445f585d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit342aaef939e1485687016700445f585d::$classMap;

        }, null, ClassLoader::class);
    }
}
