<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Rank_Math_Instant_Indexing\\phpseclib3\\' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Rank_Math_Instant_Indexing\\Webmozart\\Assert\\' => array($vendorDir . '/webmozart/assert/src'),
    'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Php81\\' => array($vendorDir . '/symfony/polyfill-php81'),
    'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Intl\\Normalizer\\' => array($vendorDir . '/symfony/polyfill-intl-normalizer'),
    'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Intl\\Grapheme\\' => array($vendorDir . '/symfony/polyfill-intl-grapheme'),
    'Rank_Math_Instant_Indexing\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Rank_Math_Instant_Indexing\\Symfony\\Contracts\\Service\\' => array($vendorDir . '/symfony/service-contracts'),
    'Rank_Math_Instant_Indexing\\Symfony\\Contracts\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher-contracts'),
    'Rank_Math_Instant_Indexing\\Symfony\\Component\\String\\' => array($vendorDir . '/symfony/string'),
    'Rank_Math_Instant_Indexing\\Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Rank_Math_Instant_Indexing\\Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'Rank_Math_Instant_Indexing\\Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Rank_Math_Instant_Indexing\\Safe\\' => array($vendorDir . '/thecodingmachine/safe/lib', $vendorDir . '/thecodingmachine/safe/deprecated', $vendorDir . '/thecodingmachine/safe/generated'),
    'Rank_Math_Instant_Indexing\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Rank_Math_Instant_Indexing\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'Rank_Math_Instant_Indexing\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'Rank_Math_Instant_Indexing\\Psr\\EventDispatcher\\' => array($vendorDir . '/psr/event-dispatcher/src'),
    'Rank_Math_Instant_Indexing\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Rank_Math_Instant_Indexing\\Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'Rank_Math_Instant_Indexing\\PhpParser\\' => array($vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'Rank_Math_Instant_Indexing\\ParagonIE\\ConstantTime\\' => array($vendorDir . '/paragonie/constant_time_encoding/src'),
    'Rank_Math_Instant_Indexing\\PackageVersions\\' => array($vendorDir . '/composer/package-versions-deprecated/src/PackageVersions'),
    'Rank_Math_Instant_Indexing\\Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'Rank_Math_Instant_Indexing\\Humbug\\PhpScoper\\' => array($vendorDir . '/humbug/php-scoper/src'),
    'Rank_Math_Instant_Indexing\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'Rank_Math_Instant_Indexing\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'Rank_Math_Instant_Indexing\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Rank_Math_Instant_Indexing\\Google\\Service\\' => array($vendorDir . '/google/apiclient-services/src'),
    'Rank_Math_Instant_Indexing\\Google\\Auth\\' => array($vendorDir . '/google/auth/src'),
    'Rank_Math_Instant_Indexing\\Google\\' => array($vendorDir . '/google/apiclient/src'),
    'Rank_Math_Instant_Indexing\\Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'Rank_Math_Instant_Indexing\\Fidry\\Console\\' => array($vendorDir . '/fidry/console/src'),
);
